# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
    - '**.md'
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    
    
    #- name: My Markdown Linter
    #  uses: ruzickap/action-my-markdown-linter@v0.0.1
      #with:
        # markdownlint config file
        #config_file: # optional
        # Debug mode
        #debug: # optional
        # Exclude files or directories
        #exclude: # optional
        # Command line parameters for fd command. "exclude" and "search_paths" parameters are ignored if this is set
        #fd_cmd_params: # optional
        # Set paths which should be recursively scanned for markdown files (*.md) and linted. By default all "*.md" files are checked
        #search_paths: # optional
    
    #- name: Markdown Linting Action
    #  uses: avto-dev/markdown-lint@v1.3.1
      #with:
        # Custom rule files (file|directory|glob|package)
        #rules: # optional
        # Configuration file (JSON, JSONC, or YAML)
        #config: # optional
        # Fix basic errors
        #fix: # optional, default is false
        # Write issues to file
        #output: # optional
        # Files to ignore/exclude
        #ignore: # optional
        # Files (directories|globs) for a work or any additional arguments
        #args: 
        
   # - name: simple-cspell
   #   uses: zwaldowski/cspell-action@1.0.0
   #   with:
        # Glob pattern of files to check
   #     paths: "**.md"
   #     config: .github/workflows/cspell.json
        # Configuration file to use. By default cspell looks for cspell.json in the current directory.
        #config: # optional
        # Exclude files matching the glob pattern
        #exclude: # optional
        # Only output the first instance of a word not found in the dictionaries.
        #unique: # optional
          
          
    - name: Create Branch
      uses: peterjgrainger/action-create-branch@v2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
      with:
        # The branch to create
        branch: 'Feature' # optional, default is release-candidate
          
    - name: GitHub Pull Request Action
      uses: repo-sync/pull-request@v2.3
      with:
        # Branch name to pull from, default is triggered branch
        source_branch: 'Feature' # optional
        # Branch name to sync to in this repo, default is master
        destination_branch: 'QA' # optional, default is master
        # Pull request title
        #pr_title: # optional
        # Pull request body
        #pr_body: # optional
        # Pull request template
        #pr_template: # optional
        # Pull request reviewers, comma-separated list (no spaces)
        pr_reviewer: 'hirenpatel35' # optional
        # Pull request assignees, comma-separated list (no spaces)
        #pr_assignee: # optional
        # Pull request labels, comma-separated list (no spaces)
        #pr_label: # optional
        # Pull request milestone
        #pr_milestone: # optional
        # Draft pull request
        #pr_draft: # optional
        # Create PR even if no changes
        #pr_allow_empty: # optional
        # GitHub token secret
        github_token: ${{ secrets.TEST_TOKEN }}      
        
       
   

   
